
# [Author: Sai Kiran Gandluri(02144549)]
# [Date: 04-09-2024]

# -*- coding: utf-8 -*-
"""SocialComputing7..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWXpJdjXCcUMCrUv6uROAkXJmrTWwPsd
"""

!pip install tweet-preprocessor

!pip install tensorflow

!pip install numpy

!pip install tensorflow

!pip install scikit-learn

from google.colab import drive
drive.mount('/content/drive')

# [Author: Sai Kiran Gandluri(02144549)]
# [Date: 04-09-2024]

# Necessary Imports
from sklearn.metrics import balanced_accuracy_score
import numpy as np
import re
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score, precision_score, recall_score
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import textwrap



# Data Cleaning Function
def clean_tweet(tweet):
    tweet = re.sub(r'http\S+', '', tweet)  # Remove URLs
    tweet = re.sub(r'@\w+', '', tweet)  # Remove mentions
    tweet = re.sub(r'#', '', tweet)  # Optional: Remove the # symbol from hashtags
    return tweet

# Data Loading and Preprocessing
def load_and_preprocess_data(filepath):
    tweet_ids, tweets, hashtags = [], [], []
    with open(filepath, 'r', encoding='utf-8') as file:
        for line in file:
            parts = line.strip().split('\t')
            tweet_ids.append(parts[0])
            tweets.append(clean_tweet(parts[2]))
            hashtags.append(parts[1] if len(parts) > 1 else None)
    return np.array(tweet_ids), np.array(tweets), np.array(hashtags)

# Model Definition
def define_model(vocab_size, embedding_dim=100, output_size=10, maxlen=100):
    model = Sequential([
        Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=maxlen),
        Bidirectional(LSTM(64, return_sequences=True)),
        Dropout(0.2),
        LSTM(32),
        Dense(64, activation='relu'),
        Dropout(0.2),
        Dense(output_size, activation='softmax')
    ])
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# Path to your data files
train_file_path = 'drive/MyDrive/data/train.txt'
val_file_path = 'drive/MyDrive/data/val.txt'
test_file_path = 'drive/MyDrive/data/test.txt'

# Loading and Preprocessing Data
train_tweet_ids, train_tweets, train_hashtags = load_and_preprocess_data(train_file_path)
val_tweet_ids, val_tweets, val_hashtags = load_and_preprocess_data(val_file_path)
test_tweet_ids, test_tweets, _ = load_and_preprocess_data(test_file_path)

# Printing few lines of CLEAN DATA after pre-processing  
def print_in_box(title, data, box_width=80):
    wrapper = textwrap.TextWrapper(width=box_width - 4)  
    dynamic_box_width = max(len(title), box_width)

    print("*" * dynamic_box_width)
    print("*", title.center(dynamic_box_width - 4), "*")
    print("*" * dynamic_box_width)

    for item in data:
        wrapped_text = wrapper.wrap(text=item)
        if not wrapped_text:  # Handle empty strings to avoid missing box lines
            print("*", " ".center(dynamic_box_width - 4), "*")
        for line in wrapped_text:
            print("*", line.center(dynamic_box_width - 4), "*")
        print("*" * dynamic_box_width)  # Optionally remove this for a continuous box without item separators

# Print cleaned TRAIN DATA samples in a box
print_in_box("Cleaned TRAIN DATA Samples", train_tweets[:5])

# Print cleaned VAL DATA samples in a box
print_in_box("Cleaned VAL DATA Samples", val_tweets[:5])


# Tokenization and Sequence Padding
tokenizer = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(train_tweets)
X_train = pad_sequences(tokenizer.texts_to_sequences(train_tweets), maxlen=100)
X_val = pad_sequences(tokenizer.texts_to_sequences(val_tweets), maxlen=100)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_tweets), maxlen=100)

# Encoding Labels (For simplicity, assuming hashtags are your labels)
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(train_hashtags)
y_val = label_encoder.transform(val_hashtags)

# Model Training
vocab_size = len(tokenizer.word_index) + 1
model = define_model(vocab_size, output_size=len(label_encoder.classes_))
callbacks = [EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True),
             ModelCheckpoint('best_model.keras', save_best_only=True, monitor='val_accuracy')]
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=5, batch_size=12, callbacks=callbacks)

# Model Evaluation on Validation Set
y_pred = model.predict(X_val, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)
print("F1-Score:", f1_score(y_val, y_pred_classes, average='weighted'))
print("Precision:", precision_score(y_val, y_pred_classes, average='weighted'))
print("Recall:", recall_score(y_val, y_pred_classes, average='weighted'))

# Model Evaluation on Validation Set
y_pred = model.predict(X_val, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)
balanced_accuracy = balanced_accuracy_score(y_val, y_pred_classes)
print("Balanced Accuracy :", balanced_accuracy)

# Evaluate the ensemble model using cross-validation
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
model1 = LogisticRegression(max_iter=1000)  # Define and train the Logistic Regression model with increased max_iter

# Update the ensemble model with the modified Logistic Regression model
ensemble_model = VotingClassifier(estimators=[('lr', model1), ('svm', model2), ('rf', model3)], voting='hard')
ensemble_scores = cross_val_score(ensemble_model, X_train_scaled, y_train, cv=5)
print("Ensemble Model Accuracy: %0.2f (+/- %0.2f)" % (ensemble_scores.mean(), ensemble_scores.std() * 2))


# Predictions on Test Data
test_pred = model.predict(X_test, verbose=0)
test_pred_classes = np.argmax(test_pred, axis=1)
predicted_hashtags = label_encoder.inverse_transform(test_pred_classes)

# Print Predictions for Test Data
for tweet_id, pred in zip(test_tweet_ids, predicted_hashtags):
    print(f"{tweet_id}\t{pred}")

